spring:
  application:
    name: mvp

  cloud.stream:
    bindings:
      shipping-out:
        destination: mvp.shipping
      shipping-in:
        destination: shipping.mvp
        group: ${spring.application.name}-shipping-group

    kafka:
      bindings:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mariadb://localhost:3306/cardb
    username: maria
    password: maria
    driver-class-name: org.mariadb.jdbc.Driver
